-   id: pycodestyle
    name: pycodestyle
    description: pycodestyle is a tool to check your Python code against some of the style conventions in PEP 8.
    entry: pycodestyle
    language: python
    types: [python]
